services:
  process1:
    container_name: process1
    build:
      context: .
      dockerfile: DockerfileNode
    env_file:
      - .env
    command: [ "./mainNode", "1", "${INITIAL_BALANCE_PROCESS1}" ]

  process2:
    container_name: process2
    build:
      context: .
      dockerfile: DockerfileNode
    env_file:
      - .env
    command: [ "./mainNode", "2", "${INITIAL_BALANCE_PROCESS2}" ]

  process3:
    container_name: process3
    build:
      context: .
      dockerfile: DockerfileNode
    env_file:
      - .env
    command: [ "./mainNode", "3", "${INITIAL_BALANCE_PROCESS3}" ]

  client:
    container_name: client
    build:
      context: .
      dockerfile: DockerfileClient
    env_file:
      - .env
    depends_on:
      - process1
      - process2
      - process3
    command: [ "./mainClient" ]
