services:
  process1:
    container_name: process1
    build:
      context: .
      dockerfile: DockerfileNode
    env_file:
      - .env
    command: [ "./mainNode", "1", "${INITIAL_BALANCE_PROCESS1}" ]
    #${INITIAL_BALANCE_PROCESS1}

  process2:
    container_name: process2
    build:
      context: .
      dockerfile: DockerfileNode
    env_file:
      - .env
    command: [ "./mainNode", "2", "${INITIAL_BALANCE_PROCESS2}" ]

  process3:
    container_name: process3
    build:
      context: .
      dockerfile: DockerfileNode
    env_file:
      - .env
    command: [ "./mainNode", "3", "${INITIAL_BALANCE_PROCESS3}" ]

  process4:
    container_name: process4
    build:
      context: .
      dockerfile: DockerfileNode
    env_file:
      - .env
    command: [ "./mainNode", "4", "${INITIAL_BALANCE_PROCESS4}" ]

  process5:
    container_name: process5
    build:
      context: .
      dockerfile: DockerfileNode
    env_file:
      - .env
    command: [ "./mainNode", "5", "${INITIAL_BALANCE_PROCESS5}" ]

  client:
    container_name: client
    build:
      context: .
      dockerfile: DockerfileClient
    env_file:
      - .env
    depends_on:
      - process1
      - process2
      - process3
      - process4
      - process5
    command: [ "./mainClient" ]
